# Generated by Django 5.2.9 on 2025-12-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default/default_profile.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
